//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureExam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureExam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            margin: 0px;
        ///            font-size: 16px;
        ///            font-family: &quot;RobotoDraft&quot;, Helvetica, Arial, sans-serif;
        ///            font-weight: 300;
        ///            line-height: 24px;
        ///            background-color: #f4f4f4;
        ///        }
        ///        .paper {
        ///            box-shadow: 0px 0px 10px 1px rgba(0, 0, 0, 0.75);
        ///        }
        ///        .header {
        ///            wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmljs {
            get {
                return ResourceManager.GetString("htmljs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:draw=&quot;urn:oasis:names:tc:opendocument:xmlns:drawing:1.0&quot; xmlns:text=&quot;urn:oasis:names:tc:opendocument:xmlns:text:1.0&quot; xmlns:form=&quot;urn:oasis:names:tc:opendocument:xmlns:form:1.0&quot;&gt;
        ///  &lt;xsl:output indent=&quot;yes&quot; encoding=&quot;ISO-8859-1&quot; method=&quot;xml&quot; /&gt;
        ///
        ///  &lt;xsl:variable name=&quot;QUESTION&quot; select = &quot;&apos;Frage&apos;&quot; /&gt;
        ///  &lt;xsl:variable name=&quot;SUBJECT&quot; select = &quot;&apos;Fach:&apos;&quot; /&gt;
        ///  
        ///  &lt;xsl:template match=&quot;text:p[not(.//draw:co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string odt {
            get {
                return ResourceManager.GetString("odt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:draw=&quot;urn:oasis:names:tc:opendocument:xmlns:drawing:1.0&quot; xmlns:text=&quot;urn:oasis:names:tc:opendocument:xmlns:text:1.0&quot; xmlns:form=&quot;urn:oasis:names:tc:opendocument:xmlns:form:1.0&quot;&gt;
        ///  &lt;xsl:output indent=&quot;yes&quot; encoding=&quot;ISO-8859-1&quot; method=&quot;xml&quot; /&gt;
        ///
        ///   &lt;xsl:template match=&quot;question&quot;&gt;
        ///      &lt;xsl:element name=&quot;question&quot;&gt;
        ///		&lt;xsl:variable name=&quot;QUESTIONNR&quot; select=&quot;@nr&quot; /&gt;
        ///		&lt;legend&gt;
        ///			&lt;xsl:value-of sele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string odt2 {
            get {
                return ResourceManager.GetString("odt2", resourceCulture);
            }
        }
    }
}
